### ISSUE TITLE
项目编译报错

### ISSUE THREAD

**Issue by Renderz** [ychengcloud/react-vite-admin#1]
renderz@renderzdeMacBook-Pro react-vite-admin % yarn build
yarn run v1.22.0
$ tsc && vite build
node_modules/@ant-design/pro-form/lib/components/ColorPicker/index.d.ts:2:40 - error TS7016: Could not find a declaration file for module 'react-color'. '/Users/renderz/github/react-vite-admin/node_modules/react-color/lib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-color` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-color';`

2 import type { SketchPickerProps } from 'react-color';
                                         ~~~~~~~~~~~~~

node_modules/@ant-design/pro-layout/lib/typings.d.ts:2:15 - error TS2305: Module '"react-router-dom"' has no exported member 'RouteComponentProps'.

2 import type { RouteComponentProps as BasicRouteProps, match } from 'react-router-dom';
                ~~~~~~~~~~~~~~~~~~~

node_modules/@ant-design/pro-layout/lib/typings.d.ts:2:55 - error TS2305: Module '"react-router-dom"' has no exported member 'match'.

2 import type { RouteComponentProps as BasicRouteProps, match } from 'react-router-dom';
                                                        ~~~~~

node_modules/@ant-design/pro-layout/lib/typings.d.ts:5:11 - error TS2694: Namespace '"/Users/renderz/github/react-vite-admin/node_modules/history/index"' has no exported member 'LocationDescriptor'.

5     to: H.LocationDescriptor;
            ~~~~~~~~~~~~~~~~~~

node_modules/@antv/g6-core/lib/index.d.ts:1:23 - error TS2688: Cannot find type definition file for '_gl-matrix@3.3.0@gl-matrix'.

**Comment by ychengcloud** [comment]
@Renderz 已经修复，原因是 build 时执行了 tsc 命令， vite 已经不需要执行此命令了。参见： https://cn.vitejs.dev/guide/features.html#npm-dependency-resolving-and-pre-bundling， 多谢！
