### ISSUE TITLE
使用 react-query 和 request.ts 文件中 axios  的二次封装 会产生一个问题

### ISSUE THREAD

**Issue by TipsyDr** [ychengcloud/react-vite-admin#4]
当我们 App.tsx 中 这个接口的 status 为 401 以及其他的 error 时 我们根本没有办法进入login 页面  所以这点是否有点问题
![image](https://user-images.githubusercontent.com/54027966/159853072-f7c7e0a3-6585-427e-9f8a-45d75f32aa76.png)

**Comment by ychengcloud** [comment]
的确，处理逻辑有问题，请更新最新代码，已经修复，谢谢！
