### ISSUE TITLE
导入Ant日期组件，无法显示中文日期，能否解决一下！

### ISSUE THREAD

**Issue by softmaxs** [ychengcloud/react-vite-admin#6]

**Comment by ychengcloud** [comment]
欢迎提交PR，一起完善项目，谢谢

**Comment by softmaxs** [comment]
就是怎么改都改不成中文，不知道是什么原因，看你能解决不。

**Comment by ychengcloud** [comment]
已解决，请更新最新代码试一下
这应该是antd 日期组件和 moment 库版本的兼容 问题，详细请参考：

https://github.com/ant-design/ant-design/issues/23891
