### ISSUE TITLE
🙋

### ISSUE THREAD

**Issue by shmily-jianjian** [ychengcloud/react-vite-admin#7]
您好，看了下您的项目有几个问题想请教下
1 看你在请求拦截那里跳转登陆用的是   window.location.href = '/login'; 然后我看您也引入了 const history = createBrowserHistory(); 是原本打算用history跳转然后不生效嘛?
2 我看 react-router-dom V6 中 unstable_HistoryRouter这个路由可以实现在js｜ts下跳转路由
3 react-router-dom中也增加了很多特别好用的 方法 createBrowserRouter 和 RouterProvider 以及Route也增加了很多属性 像loader 可以登陆拦截 errorElement可以做到errorboundary等功能
4 但是上述第三点只能通过createBrowserRouter方法实现，和我第二点又冲突了～～
5 所以我现在的问题是 如何通过  createBrowserRouter 和 RouterProvider创建路由，又能在js|ts文件下跳转路由而不是用window.location.href～～

**Comment by ychengcloud** [comment]
首先感谢关注，关于你的问题回答如下


1. 并没有这个想法
2. 此方法还是unstable 状态，并没有打算引入
3. 3 - 5 的问题，我还没有研究过，如果有更好的方法，欢迎提 PR, 一起完善项目
